-- Migration: Extend suppliers table with additional fields
-- Date: 2024-11-20
-- Description: Add country, city, province, postal code, and other address-related fields to suppliers table

-- Add new fields to suppliers table
ALTER TABLE suppliers
  ADD COLUMN IF NOT EXISTS country VARCHAR(100),
  ADD COLUMN IF NOT EXISTS city VARCHAR(100),
  ADD COLUMN IF NOT EXISTS province VARCHAR(100),
  ADD COLUMN IF NOT EXISTS postal_code VARCHAR(20),
  ADD COLUMN IF NOT EXISTS address_line2 TEXT,
  ADD COLUMN IF NOT EXISTS phone_country_code VARCHAR(10),
  ADD COLUMN IF NOT EXISTS phone_number VARCHAR(50),
  ADD COLUMN IF NOT EXISTS has_whatsapp BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS first_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS last_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS birth_date DATE,
  ADD COLUMN IF NOT EXISTS tax_id VARCHAR(50),
  ADD COLUMN IF NOT EXISTS company VARCHAR(255);

-- Create countries table with phone prefixes
CREATE TABLE IF NOT EXISTS countries (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  iso_code VARCHAR(2) NOT NULL UNIQUE,
  iso_code3 VARCHAR(3) NOT NULL UNIQUE,
  phone_prefix VARCHAR(10) NOT NULL,
  flag_emoji VARCHAR(5),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert comprehensive list of countries with phone prefixes
INSERT INTO countries (name, iso_code, iso_code3, phone_prefix, flag_emoji) VALUES
('Afganistán', 'AF', 'AFG', '+93', '🇦🇫'),
('Albania', 'AL', 'ALB', '+355', '🇦🇱'),
('Alemania', 'DE', 'DEU', '+49', '🇩🇪'),
('Andorra', 'AD', 'AND', '+376', '🇦🇩'),
('Angola', 'AO', 'AGO', '+244', '🇦🇴'),
('Antigua y Barbuda', 'AG', 'ATG', '+1268', '🇦🇬'),
('Arabia Saudí', 'SA', 'SAU', '+966', '🇸🇦'),
('Argelia', 'DZ', 'DZA', '+213', '🇩🇿'),
('Argentina', 'AR', 'ARG', '+54', '🇦🇷'),
('Armenia', 'AM', 'ARM', '+374', '🇦🇲'),
('Australia', 'AU', 'AUS', '+61', '🇦🇺'),
('Austria', 'AT', 'AUT', '+43', '🇦🇹'),
('Azerbaiyán', 'AZ', 'AZE', '+994', '🇦🇿'),
('Bahamas', 'BS', 'BHS', '+1242', '🇧🇸'),
('Bangladesh', 'BD', 'BGD', '+880', '🇧🇩'),
('Barbados', 'BB', 'BRB', '+1246', '🇧🇧'),
('Bélgica', 'BE', 'BEL', '+32', '🇧🇪'),
('Belice', 'BZ', 'BLZ', '+501', '🇧🇿'),
('Benin', 'BJ', 'BEN', '+229', '🇧🇯'),
('Bielorrusia', 'BY', 'BLR', '+375', '🇧🇾'),
('Bolivia', 'BO', 'BOL', '+591', '🇧🇴'),
('Bosnia y Herzegovina', 'BA', 'BIH', '+387', '🇧🇦'),
('Botsuana', 'BW', 'BWA', '+267', '🇧🇼'),
('Brasil', 'BR', 'BRA', '+55', '🇧🇷'),
('Brunéi', 'BN', 'BRN', '+673', '🇧🇳'),
('Bulgaria', 'BG', 'BGR', '+359', '🇧🇬'),
('Burkina Faso', 'BF', 'BFA', '+226', '🇧🇫'),
('Burundi', 'BI', 'BDI', '+257', '🇧🇮'),
('Cabo Verde', 'CV', 'CPV', '+238', '🇨🇻'),
('Camboya', 'KH', 'KHM', '+855', '🇰🇭'),
('Camerún', 'CM', 'CMR', '+237', '🇨🇲'),
('Canadá', 'CA', 'CAN', '+1', '🇨🇦'),
('Chad', 'TD', 'TCD', '+235', '🇹🇩'),
('Chile', 'CL', 'CHL', '+56', '🇨🇱'),
('China', 'CN', 'CHN', '+86', '🇨🇳'),
('Chipre', 'CY', 'CYP', '+357', '🇨🇾'),
('Colombia', 'CO', 'COL', '+57', '🇨🇴'),
('Comoras', 'KM', 'COM', '+269', '🇰🇲'),
('Congo', 'CG', 'COG', '+242', '🇨🇬'),
('Corea del Norte', 'KP', 'PRK', '+850', '🇰🇵'),
('Corea del Sur', 'KR', 'KOR', '+82', '🇰🇷'),
('Costa de Marfil', 'CI', 'CIV', '+225', '🇨🇮'),
('Costa Rica', 'CR', 'CRI', '+506', '🇨🇷'),
('Croacia', 'HR', 'HRV', '+385', '🇭🇷'),
('Cuba', 'CU', 'CUB', '+53', '🇨🇺'),
('Dinamarca', 'DK', 'DNK', '+45', '🇩🇰'),
('Dominica', 'DM', 'DMA', '+1767', '🇩🇲'),
('Ecuador', 'EC', 'ECU', '+593', '🇪🇨'),
('Egipto', 'EG', 'EGY', '+20', '🇪🇬'),
('El Salvador', 'SV', 'SLV', '+503', '🇸🇻'),
('Emiratos Árabes Unidos', 'AE', 'ARE', '+971', '🇦🇪'),
('Eritrea', 'ER', 'ERI', '+291', '🇪🇷'),
('Eslovaquia', 'SK', 'SVK', '+421', '🇸🇰'),
('Eslovenia', 'SI', 'SVN', '+386', '🇸🇮'),
('España', 'ES', 'ESP', '+34', '🇪🇸'),
('Estados Unidos', 'US', 'USA', '+1', '🇺🇸'),
('Estonia', 'EE', 'EST', '+372', '🇪🇪'),
('Etiopía', 'ET', 'ETH', '+251', '🇪🇹'),
('Filipinas', 'PH', 'PHL', '+63', '🇵🇭'),
('Finlandia', 'FI', 'FIN', '+358', '🇫🇮'),
('Francia', 'FR', 'FRA', '+33', '🇫🇷'),
('Gabón', 'GA', 'GAB', '+241', '🇬🇦'),
('Gambia', 'GM', 'GMB', '+220', '🇬🇲'),
('Georgia', 'GE', 'GEO', '+995', '🇬🇪'),
('Ghana', 'GH', 'GHA', '+233', '🇬🇭'),
('Grecia', 'GR', 'GRC', '+30', '🇬🇷'),
('Granada', 'GD', 'GRD', '+1473', '🇬🇩'),
('Guatemala', 'GT', 'GTM', '+502', '🇬🇹'),
('Guinea', 'GN', 'GIN', '+224', '🇬🇳'),
('Guinea Ecuatorial', 'GQ', 'GNQ', '+240', '🇬🇶'),
('Guinea-Bisáu', 'GW', 'GNB', '+245', '🇬🇼'),
('Guyana', 'GY', 'GUY', '+592', '🇬🇾'),
('Haití', 'HT', 'HTI', '+509', '🇭🇹'),
('Honduras', 'HN', 'HND', '+504', '🇭🇳'),
('Hungría', 'HU', 'HUN', '+36', '🇭🇺'),
('India', 'IN', 'IND', '+91', '🇮🇳'),
('Indonesia', 'ID', 'IDN', '+62', '🇮🇩'),
('Irak', 'IQ', 'IRQ', '+964', '🇮🇶'),
('Irán', 'IR', 'IRN', '+98', '🇮🇷'),
('Irlanda', 'IE', 'IRL', '+353', '🇮🇪'),
('Islandia', 'IS', 'ISL', '+354', '🇮🇸'),
('Israel', 'IL', 'ISR', '+972', '🇮🇱'),
('Italia', 'IT', 'ITA', '+39', '🇮🇹'),
('Jamaica', 'JM', 'JAM', '+1876', '🇯🇲'),
('Japón', 'JP', 'JPN', '+81', '🇯🇵'),
('Jordania', 'JO', 'JOR', '+962', '🇯🇴'),
('Kazajistán', 'KZ', 'KAZ', '+7', '🇰🇿'),
('Kenia', 'KE', 'KEN', '+254', '🇰🇪'),
('Kosovo', 'XK', 'XKX', '+383', '🇽🇰'),
('Kuwait', 'KW', 'KWT', '+965', '🇰🇼'),
('Laos', 'LA', 'LAO', '+856', '🇱🇦'),
('Lesoto', 'LS', 'LSO', '+266', '🇱🇸'),
('Letonia', 'LV', 'LVA', '+371', '🇱🇻'),
('Líbano', 'LB', 'LBN', '+961', '🇱🇧'),
('Liberia', 'LR', 'LBR', '+231', '🇱🇷'),
('Libia', 'LY', 'LBY', '+218', '🇱🇾'),
('Liechtenstein', 'LI', 'LIE', '+423', '🇱🇮'),
('Lituania', 'LT', 'LTU', '+370', '🇱🇹'),
('Luxemburgo', 'LU', 'LUX', '+352', '🇱🇺'),
('Madagascar', 'MG', 'MDG', '+261', '🇲🇬'),
('Malasia', 'MY', 'MYS', '+60', '🇲🇾'),
('Malaui', 'MW', 'MWI', '+265', '🇲🇼'),
('Maldivas', 'MV', 'MDV', '+960', '🇲🇻'),
('Malí', 'ML', 'MLI', '+223', '🇲🇱'),
('Malta', 'MT', 'MLT', '+356', '🇲🇹'),
('Marruecos', 'MA', 'MAR', '+212', '🇲🇦'),
('Mauricio', 'MU', 'MUS', '+230', '🇲🇺'),
('Mauritania', 'MR', 'MRT', '+222', '🇲🇷'),
('México', 'MX', 'MEX', '+52', '🇲🇽'),
('Moldavia', 'MD', 'MDA', '+373', '🇲🇩'),
('Mónaco', 'MC', 'MCO', '+377', '🇲🇨'),
('Mongolia', 'MN', 'MNG', '+976', '🇲🇳'),
('Montenegro', 'ME', 'MNE', '+382', '🇲🇪'),
('Mozambique', 'MZ', 'MOZ', '+258', '🇲🇿'),
('Namibia', 'NA', 'NAM', '+264', '🇳🇦'),
('Nauru', 'NR', 'NRU', '+674', '🇳🇷'),
('Nepal', 'NP', 'NPL', '+977', '🇳🇵'),
('Nicaragua', 'NI', 'NIC', '+505', '🇳🇮'),
('Níger', 'NE', 'NER', '+227', '🇳🇪'),
('Nigeria', 'NG', 'NGA', '+234', '🇳🇬'),
('Noruega', 'NO', 'NOR', '+358', '🇳🇴'),
('Nueva Zelanda', 'NZ', 'NZL', '+64', '🇳🇿'),
('Omán', 'OM', 'OMN', '+968', '🇴🇲'),
('Países Bajos', 'NL', 'NLD', '+31', '🇳🇱'),
('Pakistán', 'PK', 'PAK', '+92', '🇵🇰'),
('Palestina', 'PS', 'PSE', '+970', '🇵🇸'),
('Panamá', 'PA', 'PAN', '+507', '🇵🇦'),
('Papúa Nueva Guinea', 'PG', 'PNG', '+675', '🇵🇬'),
('Paraguay', 'PY', 'PRY', '+595', '🇵🇾'),
('Perú', 'PE', 'PER', '+51', '🇵🇪'),
('Polonia', 'PL', 'POL', '+48', '🇵🇱'),
('Portugal', 'PT', 'PRT', '+351', '🇵🇹'),
('Qatar', 'QA', 'QAT', '+974', '🇶🇦'),
('Reino Unido', 'GB', 'GBR', '+44', '🇬🇧'),
('República Centroafricana', 'CF', 'CAF', '+236', '🇨🇫'),
('República Checa', 'CZ', 'CZE', '+420', '🇨🇿'),
('República del Congo', 'CD', 'COD', '+243', '🇨🇩'),
('República Dominicana', 'DO', 'DOM', '+1809', '🇩🇴'),
('Ruanda', 'RW', 'RWA', '+250', '🇷🇼'),
('Rumania', 'RO', 'ROU', '+40', '🇷🇴'),
('Rusia', 'RU', 'RUS', '+7', '🇷🇺'),
('Samoa', 'WS', 'WSM', '+685', '🇼🇸'),
('San Marino', 'SM', 'SMR', '+378', '🇸🇲'),
('San Vicente y las Granadinas', 'VC', 'VCT', '+1784', '🇻🇨'),
('Santa Lucía', 'LC', 'LCA', '+1758', '🇱🇨'),
('Santo Tomé y Príncipe', 'ST', 'STP', '+239', '🇸🇹'),
('Senegal', 'SN', 'SEN', '+221', '🇸🇳'),
('Serbia', 'RS', 'SRB', '+381', '🇷🇸'),
('Seychelles', 'SC', 'SYC', '+248', '🇸🇨'),
('Sierra Leona', 'SL', 'SLE', '+232', '🇸🇱'),
('Singapur', 'SG', 'SGP', '+65', '🇸🇬'),
('Siria', 'SY', 'SYR', '+963', '🇸🇾'),
('Somalia', 'SO', 'SOM', '+252', '🇸🇴'),
('Sri Lanka', 'LK', 'LKA', '+94', '🇱🇰'),
('Sudáfrica', 'ZA', 'ZAF', '+27', '🇿🇦'),
('Sudán', 'SD', 'SDN', '+249', '🇸🇩'),
('Sudán del Sur', 'SS', 'SSD', '+211', '🇸🇸'),
('Suecia', 'SE', 'SWE', '+46', '🇸🇪'),
('Suiza', 'CH', 'CHE', '+41', '🇨🇭'),
('Surinam', 'SR', 'SUR', '+597', '🇸🇷'),
('Suazilandia', 'SZ', 'SWZ', '+268', '🇸🇿'),
('Tailandia', 'TH', 'THA', '+66', '🇹🇭'),
('Tanzania', 'TZ', 'TZA', '+255', '🇹🇿'),
('Timor Oriental', 'TL', 'TLS', '+670', '🇹🇱'),
('Togo', 'TG', 'TGO', '+228', '🇹🇬'),
('Tonga', 'TO', 'TON', '+676', '🇹🇴'),
('Trinidad y Tobago', 'TT', 'TTO', '+1868', '🇹🇹'),
('Túnez', 'TN', 'TUN', '+216', '🇹🇳'),
('Turkmenistán', 'TM', 'TKM', '+993', '🇹🇲'),
('Turquía', 'TR', 'TUR', '+90', '🇹🇷'),
('Tuvalu', 'TV', 'TUV', '+688', '🇹🇻'),
('Ucrania', 'UA', 'UKR', '+380', '🇺🇦'),
('Uganda', 'UG', 'UGA', '+256', '🇺🇬'),
('Uruguay', 'UY', 'URY', '+598', '🇺🇾'),
('Uzbekistán', 'UZ', 'UZB', '+998', '🇺🇿'),
('Vanuatu', 'VU', 'VUT', '+678', '🇻🇺'),
('Vaticano', 'VA', 'VAT', '+39', '🇻🇦'),
('Venezuela', 'VE', 'VEN', '+58', '🇻🇪'),
('Vietnam', 'VN', 'VNM', '+84', '🇻🇳'),
('Yemen', 'YE', 'YEM', '+967', '🇾🇪'),
('Zambia', 'ZM', 'ZMB', '+260', '🇿🇲'),
('Zimbabue', 'ZW', 'ZWE', '+263', '🇿🇼')
ON CONFLICT (iso_code) DO NOTHING;

-- Create index for better performance
CREATE INDEX IF NOT EXISTS idx_countries_iso_code ON countries(iso_code);

-- Create trigger for updated_at
CREATE TRIGGER update_countries_updated_at 
  BEFORE UPDATE ON countries
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

